CREATE TABLE customer (
  address_ds STRING COMMENT 'Address of PoC',
  channel_cd STRING COMMENT 'Code of Channel ',
  channel_ds STRING COMMENT 'Larger grouping of sales channels i.e. 
Traditional trade on (on premise pocs, typically service lower lsm groups, value and core brand, bulk packs and returnables usually) ex: popular bar, 
Traditional trade off (same as above but off premise) ex: pit stop
Modern trade on (on premise pocs, typically servicing higher lsm groups, elevated core plus and high end mix, one way packs usually) , 
Modern trade off (same as above but off premise), 
wholesalers (pocs that sell to other resellers - do not have an exclusive territorial distribution agreement with ABI - competes with ABI direct sales), 
3PD (pocs that have an exclusive territorial agreement with ABI - not in direct competition with ABI direct sales)',
  channel_typ STRING COMMENT 'Off x On',
  city_nm STRING COMMENT 'City of Poc ',
  coordinate_lat STRING COMMENT 'Global location: Latitude  co-ordinate',
  coordinate_log STRING COMMENT 'Global location: Longitude co-ordinate',
  country_cd STRING COMMENT 'Current country of extraction. Always two chars like "BR", "CO", "US", "ZA"',
  credit_limit_val STRING COMMENT 'credit limit available for customer (Data of a numerical nature that expresses a monetary amount)',
  credit_payment_terms_typ STRING COMMENT 'Credit informations: Description of payment terms',
  customer_bees_cd STRING COMMENT 'Internal ID in B2B',
  customer_bk STRING COMMENT 'Id that identify the Customer or Point of Consumption (PoC) across all tables',
  customer_erp_cd STRING COMMENT 'customer code in original source system',
  customer_nm STRING COMMENT 'Name of the Point of Consumption (PoC) and not the poc owner ',
  intercompany_flg STRING COMMENT 'Identifies whether a customer is an intercompany or not',
  customer_potential_cls STRING COMMENT 'customer size classification based on purchasing behavior',
  customer_socioeconomic_cls STRING COMMENT 'Economic Level of PoC',
  customer_stt STRING COMMENT 'Status of Point of Consumption (PoC) for Sales (Active / Inactive)',
  customer_updated_dtm STRING COMMENT 'Last date the record was updated',
  dt_reference_ts STRING COMMENT 'The last date that each record was created/updated at the source system.',
  payment_methods_cls STRING COMMENT 'Description of payment methods',
  poc_size_cls STRING COMMENT 'PoC Size classification ',
  segment_cd STRING COMMENT 'Code Segment',
  segment_nm STRING COMMENT 'retailer, wholesaler, key accounts, ddcs',
  subsegment_cd STRING COMMENT 'Code Subsegment ',
  subsegment_nm STRING COMMENT 'retailer sublevel, key accounts breakdown, ddcs subsegment',
  src_region_nm STRING COMMENT 'ABI Region Name (AFR, NAZ, EUR, APAC, SAZ, MAZ).',
  src_sys_nm STRING COMMENT 'Source system name. ',
  src_country_cd STRING COMMENT 'Related to the ISO Code of the Country. Use the Alpha-2 code that is an international country code identification - https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes )',
  state_nm STRING COMMENT 'State of Poc',
  subchannel_cd STRING COMMENT 'Code of subchannel ',
  subchannel_nm STRING COMMENT 'Detailed breakouts of the above sales channels ex: Restaurant, Bar, Store ',
  zipcode_cd STRING COMMENT 'Zipcode or Postal Code of PoC')
USING delta
TBLPROPERTIES (
  'delta.minReaderVersion' = '1',
  'delta.minWriterVersion' = '2')